global:
  slack_api_url: '<insert slack hook>'

route:
  receiver: 'slack-notifications'
  group_by: [label1, label2] # if you want to group by labels
  group_interval: 10s
  group_wait: 10s 

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '<insert slack channel>'
